
def fun_a():
    raise Exception
    print "I'm here"

fun_a()
print "still here"
